import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
import { Provider } from "react-redux";
import { store } from "../redux/store";
export const metadata: Metadata = {
  title: "Palatte App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head><link rel="shortcut icon" href="https://img.freepik.com/premium-vector/black-white-logo-with-letter-p-it_853558-5013.jpg" /></head>
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
  );
}
